apiVersion: v1
kind: Service
metadata:
  name: {{ include "vikunja.fullname" . }}-database
  labels:
    {{ include "vikunja.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP