apiVersion: v1
kind: Service
metadata:
  name: {{ include "vikunja.fullname" . }}-frontend
  labels:
    {{ include "vikunja.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: http
